const std = @import("std");

/// luau: complete, idiomatic Zig bindings to the Luau C API.
///
/// This build:
///   1. compiles the vendored Luau C++ sources (Common, Ast, Bytecode, Compiler,
///      VM and optionally CodeGen) into a single static library, giving the public
///      `lua_*` / `luau_*` symbols `extern "C"` linkage and LUA_USE_LONGJMP error
///      handling (the configuration Luau documents for use from non-C++ languages);
///   2. runs `translate-c` over the public headers to produce the raw `bindings`
///      module (ABI-correct declarations that resolve against the static library);
///   3. exposes the idiomatic `luau` module (src/root.zig) layered on top.
pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // ---- user-facing options -------------------------------------------------
    const vector_size = b.option(
        u32,
        "vector_size",
        "LUA_VECTOR_SIZE: number of float components in the native vector type, 3 or 4 (default 3)",
    ) orelse 3;
    if (vector_size != 3 and vector_size != 4) {
        std.debug.panic("vector_size must be 3 or 4, got {d}", .{vector_size});
    }
    const enable_codegen = b.option(
        bool,
        "codegen",
        "Build the Luau native code generation (JIT) backend (default true)",
    ) orelse true;

    const luau_dep = b.dependency("luau_src", .{});

    // ---- compile-time configuration visible to Zig code ----------------------
    const opts = b.addOptions();
    opts.addOption(u32, "vector_size", vector_size);
    opts.addOption(bool, "codegen", enable_codegen);
    const config_mod = opts.createModule();

    // ---- the vendored Luau C++ static library --------------------------------
    const luau_lib = buildLuauLib(b, target, optimize, luau_dep, vector_size, enable_codegen);
    b.installArtifact(luau_lib);

    // ---- raw bindings via translate-c ----------------------------------------
    // The umbrella header is generated inline (rather than a checked-in src/c.h)
    // so the full set of translated headers lives in one place: this build file.
    // translate-c sees LUA_API/… as plain `extern`; the static library gives the
    // same symbols `extern "C"` linkage, so declarations resolve 1:1.
    const umbrella = b.addWriteFiles().add("luau_bindings.h",
        \\// Generated by build.zig — the complete C-callable Luau surface fed to translate-c.
        \\#include "lua.h"          // core VM C API (+ luaconf.h)
        \\#include "lualib.h"       // standard libraries + luaL_* helpers
        \\#include "luacode.h"      // Luau source -> bytecode compiler
        \\#include "luacodegen.h"   // native code generation (JIT)
        \\#include "Luau/Require.h" // require-by-string (already a C API)
        \\#include "Luau/Bytecode.h"// bytecode opcode/type enums
        \\#include "shim.h"    // extern "C" shims over the Luau C++ APIs
        \\
    );
    const tc = b.addTranslateC(.{
        .root_source_file = umbrella,
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    tc.addIncludePath(luau_dep.path("VM/include"));
    tc.addIncludePath(luau_dep.path("Compiler/include"));
    tc.addIncludePath(luau_dep.path("CodeGen/include"));
    tc.addIncludePath(luau_dep.path("Require/include"));
    tc.addIncludePath(luau_dep.path("Common/include"));
    tc.addIncludePath(b.path("shim"));
    // Parse as C: LUA_API expands to plain `extern` (the library gives the real
    // symbols `extern "C"` linkage, so the names still match 1:1).
    tc.defineCMacro("LUA_API", "extern");
    tc.defineCMacro("LUACODE_API", "extern");
    tc.defineCMacro("LUACODEGEN_API", "extern");
    tc.defineCMacro("LUA_VECTOR_SIZE", b.fmt("{d}", .{vector_size}));
    const c_mod = tc.createModule();

    // ---- the idiomatic, public module ----------------------------------------
    const luau_mod = b.addModule("luau", .{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .link_libcpp = true,
    });
    luau_mod.addImport("bindings", c_mod);
    luau_mod.addImport("config", config_mod);
    luau_mod.linkLibrary(luau_lib);

    // ---- tests ---------------------------------------------------------------
    // The suite lives in tests/ and consumes the public `luau` module exactly as
    // a downstream user would.
    const test_mod = b.createModule(.{
        .root_source_file = b.path("tests/root.zig"),
        .target = target,
        .optimize = optimize,
    });
    test_mod.addImport("luau", luau_mod);

    const tests = b.addTest(.{ .root_module = test_mod });
    const run_tests = b.addRunArtifact(tests);
    const test_step = b.step("test", "Run the library test suite");
    test_step.dependOn(&run_tests.step);

    // ---- coverage: gate the C API, report the C++ surface honestly -----------
    const cov_run = b.addSystemCommand(&.{"sh"});
    cov_run.addFileArg(b.path("tools/coverage.sh")); // absolute: runs from any cwd
    cov_run.addFileArg(tc.getOutput()); // (A) authoritative list of bound symbols
    cov_run.addDirectoryArg(b.path("src")); //      the idiomatic wrappers (lua/ + luau/)
    cov_run.addDirectoryArg(b.path("shim")); //     our shimmed C++ entry points (shim/**/*.h)
    // (B) Luau's C++ public headers, for the informational surface report:
    cov_run.addDirectoryArg(luau_dep.path("Ast/include"));
    cov_run.addDirectoryArg(luau_dep.path("Compiler/include"));
    cov_run.addDirectoryArg(luau_dep.path("Config/include"));
    cov_run.addDirectoryArg(luau_dep.path("Bytecode/include"));
    cov_run.addDirectoryArg(luau_dep.path("CodeGen/include"));
    cov_run.addDirectoryArg(luau_dep.path("Analysis/include"));
    cov_run.has_side_effects = true;
    const cov_step = b.step("coverage", "Gate C-API coverage; report C++ surface coverage");
    cov_step.dependOn(&cov_run.step);

    // ---- api: inventory the real public C++ surface (clang AST) --------------
    const api_run = b.addSystemCommand(&.{"python3"});
    api_run.addFileArg(b.path("tools/api_inventory.py")); // absolute: runs from any cwd
    api_run.addDirectoryArg(luau_dep.path(".")); // the vendored Luau source root
    if (b.args) |args| api_run.addArgs(args); // e.g. `zig build api -- --list Ast`
    api_run.has_side_effects = true;
    const api_step = b.step("api", "Inventory Luau's public C++ API (what matters vs internal)");
    api_step.dependOn(&api_run.step);

    // ---- gaps: per-module shim coverage gap map (dedicated, no `--` needed) ---
    const gaps_run = b.addSystemCommand(&.{"python3"});
    gaps_run.addFileArg(b.path("tools/api_inventory.py"));
    gaps_run.addDirectoryArg(luau_dep.path("."));
    gaps_run.addArg("--gaps");
    if (b.args) |args| gaps_run.addArgs(args); // optional module, e.g. `zig build gaps -- Ast`
    gaps_run.has_side_effects = true;
    const gaps_step = b.step("gaps", "Per-module shim coverage gap map (add -- <Module> to drill in)");
    gaps_step.dependOn(&gaps_run.step);

    // ---- examples ------------------------------------------------------------
    const example_step = b.step("examples", "Build and run the examples");
    for (examples) |ex| {
        const ex_mod = b.createModule(.{
            .root_source_file = b.path(ex.path),
            .target = target,
            .optimize = optimize,
        });
        ex_mod.addImport("luau", luau_mod);
        const ex_exe = b.addExecutable(.{ .name = ex.name, .root_module = ex_mod });
        b.installArtifact(ex_exe);
        const run = b.addRunArtifact(ex_exe);
        if (b.args) |args| run.addArgs(args);
        const single = b.step(ex.name, b.fmt("Run the '{s}' example", .{ex.name}));
        single.dependOn(&run.step);
        example_step.dependOn(&run.step);
    }
}

const Example = struct { name: []const u8, path: []const u8 };
const examples = [_]Example{
    .{ .name = "embedding", .path = "examples/embedding.zig" },
    .{ .name = "zig-functions", .path = "examples/zig_functions.zig" },
    .{ .name = "usertypes", .path = "examples/usertypes.zig" },
    .{ .name = "modules", .path = "examples/modules.zig" },
    .{ .name = "tables", .path = "examples/tables.zig" },
    .{ .name = "compiling", .path = "examples/compiling.zig" },
    .{ .name = "parsing", .path = "examples/parsing.zig" },
    .{ .name = "ast-types", .path = "examples/ast_types.zig" },
    .{ .name = "analysis", .path = "examples/analysis.zig" },
    .{ .name = "config", .path = "examples/config.zig" },
    .{ .name = "require", .path = "examples/require.zig" },
    .{ .name = "bytecode", .path = "examples/bytecode.zig" },
    .{ .name = "coroutines", .path = "examples/coroutines.zig" },
};

/// Compile the vendored Luau C++ into one static library.
fn buildLuauLib(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    dep: *std.Build.Dependency,
    vector_size: u32,
    enable_codegen: bool,
) *std.Build.Step.Compile {
    const mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .link_libcpp = true,
        // Luau's VM relies on tagged pointers / deliberate integer wraparound that
        // Zig's C UBSan flags as errors; the upstream build does not use UBSan.
        .sanitize_c = .off,
    });

    // public include directories (Luau/*.h and the C headers)
    mod.addIncludePath(dep.path("Common/include"));
    mod.addIncludePath(dep.path("Ast/include"));
    mod.addIncludePath(dep.path("Bytecode/include"));
    mod.addIncludePath(dep.path("Compiler/include"));
    mod.addIncludePath(dep.path("Config/include"));
    mod.addIncludePath(dep.path("Require/include"));
    mod.addIncludePath(dep.path("Analysis/include"));
    mod.addIncludePath(dep.path("VM/include"));
    mod.addIncludePath(dep.path("CodeGen/include"));
    // private source directories (internal headers included by name)
    mod.addIncludePath(dep.path("Compiler/src"));
    mod.addIncludePath(dep.path("Analysis/src"));
    mod.addIncludePath(dep.path("Require/src"));
    mod.addIncludePath(dep.path("VM/src"));
    mod.addIncludePath(dep.path("CodeGen/src"));

    // Give the public API C linkage and use setjmp/longjmp for error propagation
    // (rather than C++ exceptions) so it is safe and ergonomic to call from Zig.
    mod.addCMacro("LUA_API", "extern \"C\"");
    mod.addCMacro("LUACODE_API", "extern \"C\"");
    mod.addCMacro("LUACODEGEN_API", "extern \"C\"");
    mod.addCMacro("LUA_USE_LONGJMP", "1");
    mod.addCMacro("LUA_VECTOR_SIZE", b.fmt("{d}", .{vector_size}));

    const flags: []const []const u8 = &.{
        "-std=c++17",
        "-fno-math-errno", // let the compiler lower sqrt() etc. to a single instruction
    };

    mod.addCSourceFiles(.{ .root = dep.path("Common/src"), .files = common_src, .flags = flags, .language = .cpp });
    mod.addCSourceFiles(.{ .root = dep.path("Ast/src"), .files = ast_src, .flags = flags, .language = .cpp });
    mod.addCSourceFiles(.{ .root = dep.path("Bytecode/src"), .files = bytecode_src, .flags = flags, .language = .cpp });
    mod.addCSourceFiles(.{ .root = dep.path("Compiler/src"), .files = compiler_src, .flags = flags, .language = .cpp });
    mod.addCSourceFiles(.{ .root = dep.path("Config/src"), .files = config_src, .flags = flags, .language = .cpp });
    mod.addCSourceFiles(.{ .root = dep.path("Require/src"), .files = require_src, .flags = flags, .language = .cpp });
    mod.addCSourceFiles(.{ .root = dep.path("Analysis/src"), .files = analysis_src, .flags = flags, .language = .cpp });
    mod.addCSourceFiles(.{ .root = dep.path("VM/src"), .files = vm_src, .flags = flags, .language = .cpp });
    if (enable_codegen) {
        mod.addCSourceFiles(.{ .root = dep.path("CodeGen/src"), .files = codegen_src, .flags = flags, .language = .cpp });
    }

    // our extern "C" shims over the Luau C++ APIs — every shim/**/*.cpp, so a new
    // module is just new files (no build edit needed).
    mod.addIncludePath(b.path("shim"));
    mod.addCSourceFiles(.{ .root = b.path("shim"), .files = collectCpp(b, "shim"), .flags = flags, .language = .cpp });

    return b.addLibrary(.{ .name = "luau", .root_module = mod, .linkage = .static });
}

/// Recursively collect every `*.cpp` under `root`, returning paths relative to
/// `root` (so `shim/**/*.cpp` is compiled without listing files by hand).
fn collectCpp(b: *std.Build, root: []const u8) []const []const u8 {
    const io = b.graph.io;
    var dir = b.build_root.handle.openDir(io, root, .{ .iterate = true }) catch |e|
        std.debug.panic("cannot open '{s}': {s}", .{ root, @errorName(e) });
    defer dir.close(io);
    var walker = dir.walk(b.allocator) catch @panic("oom");
    defer walker.deinit();
    var files: std.ArrayList([]const u8) = .empty;
    while (walker.next(io) catch @panic("walk failed")) |entry| {
        if (entry.kind == .file and std.mem.endsWith(u8, entry.path, ".cpp"))
            files.append(b.allocator, b.dupe(entry.path)) catch @panic("oom");
    }
    return files.toOwnedSlice(b.allocator) catch @panic("oom");
}

// ---- Luau 0.726 source file lists (from Sources.cmake) -----------------------

const common_src = &[_][]const u8{
    "BytecodeWire.cpp", "StringUtils.cpp", "TimeTrace.cpp",
};

const ast_src = &[_][]const u8{
    "Allocator.cpp", "Ast.cpp",      "Confusables.cpp", "Cst.cpp",
    "Lexer.cpp",     "Location.cpp", "Parser.cpp",      "PrettyPrinter.cpp",
};

const bytecode_src = &[_][]const u8{
    "BytecodeBuilder.cpp", "BytecodeGraph.cpp",
};

const config_src = &[_][]const u8{
    "Config.cpp", "LinterConfig.cpp", "LuauConfig.cpp",
};

const require_src = &[_][]const u8{
    "AliasCycleTracker.cpp", "Navigation.cpp",  "PathUtilities.cpp",
    "Require.cpp",           "RequireImpl.cpp", "RequireNavigator.cpp",
};

const analysis_src = &[_][]const u8{
    "Anyification.cpp",                     "ApplyTypeFunction.cpp",          "AstJsonEncoder.cpp",
    "AstQuery.cpp",                         "AstUtils.cpp",                   "Autocomplete.cpp",
    "AutocompleteCore.cpp",                 "BuiltinDefinitions.cpp",         "BuiltinTypeFunctions.cpp",
    "Clone.cpp",                            "Constraint.cpp",                 "ConstraintGenerator.cpp",
    "ConstraintGraph.cpp",                  "ConstraintSolver.cpp",           "ControlFlowGraph.cpp",
    "DataFlowGraph.cpp",                    "DcrLogger.cpp",                  "Def.cpp",
    "DumpCFG.cpp",                          "EmbeddedBuiltinDefinitions.cpp", "Error.cpp",
    "ExpectedTypeVisitor.cpp",              "FileResolver.cpp",               "FragmentAutocomplete.cpp",
    "Frontend.cpp",                         "Generalization.cpp",             "GlobalTypes.cpp",
    "Instantiation.cpp",                    "Instantiation2.cpp",             "IostreamHelpers.cpp",
    "IterativeTypeFunctionTypeVisitor.cpp", "IterativeTypeVisitor.cpp",       "JsonEmitter.cpp",
    "LValue.cpp",                           "Linter.cpp",                     "Module.cpp",
    "NativeStackGuard.cpp",                 "NonStrictTypeChecker.cpp",       "Normalize.cpp",
    "OverloadResolver.cpp",                 "Quantify.cpp",                   "RecursionCounter.cpp",
    "Refinement.cpp",                       "RequireTracer.cpp",              "Scope.cpp",
    "Simplify.cpp",                         "StructuralTypeEquality.cpp",     "Substitution.cpp",
    "Subtyping.cpp",                        "SubtypingUnifier.cpp",           "Symbol.cpp",
    "TableLiteralInference.cpp",            "ToDot.cpp",                      "ToString.cpp",
    "TopoSortStatements.cpp",               "TxnLog.cpp",                     "Type.cpp",
    "TypeArena.cpp",                        "TypeAttach.cpp",                 "TypeChecker2.cpp",
    "TypeFunction.cpp",                     "TypeFunctionError.cpp",          "TypeFunctionReductionGuesser.cpp",
    "TypeFunctionRuntime.cpp",              "TypeFunctionRuntimeBuilder.cpp", "TypeIds.cpp",
    "TypeInfer.cpp",                        "TypeOrPack.cpp",                 "TypePack.cpp",
    "TypePath.cpp",                         "TypeUtils.cpp",                  "TypedAllocator.cpp",
    "Unifiable.cpp",                        "Unifier.cpp",                    "Unifier2.cpp",
    "UserDefinedTypeFunction.cpp",
};

const compiler_src = &[_][]const u8{
    "BuiltinFolding.cpp", "Builtins.cpp",   "Compiler.cpp", "ConstantFolding.cpp",
    "CostModel.cpp",      "TableShape.cpp", "Types.cpp",    "ValueTracking.cpp",
    "lcode.cpp",
};

const vm_src = &[_][]const u8{
    "lapi.cpp",      "laux.cpp",       "lbaselib.cpp",  "lbitlib.cpp",
    "lbuffer.cpp",   "lbuflib.cpp",    "lbuiltins.cpp", "lclass.cpp",
    "lclasslib.cpp", "lcorolib.cpp",   "ldblib.cpp",    "ldebug.cpp",
    "ldo.cpp",       "lfunc.cpp",      "lgc.cpp",       "lgcdebug.cpp",
    "linit.cpp",     "lintlib.cpp",    "lmathlib.cpp",  "lmem.cpp",
    "lnumprint.cpp", "lobject.cpp",    "loslib.cpp",    "lperf.cpp",
    "lstate.cpp",    "lstring.cpp",    "lstrlib.cpp",   "ltable.cpp",
    "ltablib.cpp",   "ltm.cpp",        "ludata.cpp",    "lutf8lib.cpp",
    "lveclib.cpp",   "lvmexecute.cpp", "lvmload.cpp",   "lvmutils.cpp",
};

const codegen_src = &[_][]const u8{
    "AssemblyBuilderA64.cpp",  "AssemblyBuilderX64.cpp", "BytecodeAnalysis.cpp",
    "BytecodeSummary.cpp",     "CodeAllocator.cpp",      "CodeBlockUnwind.cpp",
    "CodeGen.cpp",             "CodeGenA64.cpp",         "CodeGenAssembly.cpp",
    "CodeGenContext.cpp",      "CodeGenUtils.cpp",       "CodeGenX64.cpp",
    "EmitBuiltinsX64.cpp",     "EmitCommonX64.cpp",      "EmitInstructionX64.cpp",
    "IrAnalysis.cpp",          "IrBuilder.cpp",          "IrCallWrapperX64.cpp",
    "IrDump.cpp",              "IrLoweringA64.cpp",      "IrLoweringX64.cpp",
    "IrRegAllocA64.cpp",       "IrRegAllocX64.cpp",      "IrTranslateBuiltins.cpp",
    "IrTranslation.cpp",       "IrUtils.cpp",            "IrValueLocationTracking.cpp",
    "NativeProtoExecData.cpp", "NativeState.cpp",        "OptimizeConstProp.cpp",
    "OptimizeDeadStore.cpp",   "OptimizeFinalX64.cpp",   "SharedCodeAllocator.cpp",
    "UnwindBuilderDwarf2.cpp", "UnwindBuilderWin.cpp",   "lcodegen.cpp",
};
