// Umbrella for the Luau C++ shims — included by the translate-c umbrella so the
// idiomatic Zig layer can reach every shimmed symbol. One #include per module;
// agents add new modules here (or, ideally, this is regenerated).
#pragma once

#include "common.h"
#include "handles.h"
#include "alloc.h"

#include "ast/ast.h"
#include "ast/cst.h"
#include "ast/builder.h"
#include "ast/prettyprint.h"
#include "ast/lexer.h"
#include "ast/attributes.h"
#include "ast/json.h"
#include "compiler/errors.h"
#include "config/config.h"
#include "analysis/analysis.h"
#include "analysis/builtins.h"
#include "analysis/query.h"
#include "analysis/types.h"
#include "analysis/project.h"
#include "analysis/complete.h"
#include "analysis/relations.h"
#include "analysis/typeutils.h"
#include "analysis/normalize.h"
#include "analysis/transforms.h"
#include "analysis/module.h"
#include "analysis/fragment.h"
#include "analysis/linter.h"
#include "analysis/dfg.h"
#include "analysis/locate.h"
#include "analysis/documentation.h"
#include "analysis/viz.h"
#include "analysis/scan.h"
#include "analysis/polarity.h"
#include "analysis/diagnostics.h"
#include "analysis/requirepath.h"
#include "analysis/signatures.h"
#include "codegen/codegen.h"
#include "codegen/asm_x64.h"
#include "codegen/asm_a64.h"
#include "codegen/ir.h"
#include "bytecode/bytecode.h"
#include "bytecode/graph.h"
